I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/SCRIPT/battle/battle_gui.rpy", line 8, in prepare_screen
    screen main_w_data_screen():
  File "game/SCRIPT/battle/battle_gui.rpy", line 8, in prepare
    screen main_w_data_screen():
  File "game/SCRIPT/battle/battle_gui.rpy", line 15, in prepare
    fixed:
  File "game/SCRIPT/battle/battle_gui.rpy", line 15, in prepare
    fixed:
Exception: A screen named rombo_screen does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 617, in main
    run(restart)
  File "renpy/main.py", line 97, in run
    renpy.display.screen.prepare_screens()
  File "renpy/display/screen.py", line 939, in prepare_screens
    s.ast.prepare_screen()
  File "game/SCRIPT/battle/battle_gui.rpy", line 8, in prepare_screen
    screen main_w_data_screen():
  File "game/SCRIPT/battle/battle_gui.rpy", line 8, in prepare
    screen main_w_data_screen():
  File "game/SCRIPT/battle/battle_gui.rpy", line 15, in prepare
    fixed:
  File "game/SCRIPT/battle/battle_gui.rpy", line 15, in prepare
    fixed:
  File "renpy/sl2/slast.py", line 1791, in prepare
    raise Exception("A screen named {} does not exist.".format(self.target))
Exception: A screen named rombo_screen does not exist.

